[build]
  command = "npm ci --no-audit --no-fund --prefer-offline=false && npm run build"
  publish = "dist"

[build.environment]
  NPM_CONFIG_CACHE = "/opt/buildhome/tmp/.npm"
  NODE_VERSION = "22.16.0"